# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from multibody_msgs/JointState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class JointState(genpy.Message):
  _md5sum = "bddaa9375f139e95c4ae322dbc609833"
  _type = "multibody_msgs/JointState"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 q
float64 qdot
float64 tau
float64 q_out
float64 qd_out
float64 tau_out
float64 temperature
# nan: Not available; 0: False; 1: True
float64 homed
float64 locked
"""
  __slots__ = ['q','qdot','tau','q_out','qd_out','tau_out','temperature','homed','locked']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       q,qdot,tau,q_out,qd_out,tau_out,temperature,homed,locked

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(JointState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.q is None:
        self.q = 0.
      if self.qdot is None:
        self.qdot = 0.
      if self.tau is None:
        self.tau = 0.
      if self.q_out is None:
        self.q_out = 0.
      if self.qd_out is None:
        self.qd_out = 0.
      if self.tau_out is None:
        self.tau_out = 0.
      if self.temperature is None:
        self.temperature = 0.
      if self.homed is None:
        self.homed = 0.
      if self.locked is None:
        self.locked = 0.
    else:
      self.q = 0.
      self.qdot = 0.
      self.tau = 0.
      self.q_out = 0.
      self.qd_out = 0.
      self.tau_out = 0.
      self.temperature = 0.
      self.homed = 0.
      self.locked = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_9d().pack(_x.q, _x.qdot, _x.tau, _x.q_out, _x.qd_out, _x.tau_out, _x.temperature, _x.homed, _x.locked))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 72
      (_x.q, _x.qdot, _x.tau, _x.q_out, _x.qd_out, _x.tau_out, _x.temperature, _x.homed, _x.locked,) = _get_struct_9d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_9d().pack(_x.q, _x.qdot, _x.tau, _x.q_out, _x.qd_out, _x.tau_out, _x.temperature, _x.homed, _x.locked))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 72
      (_x.q, _x.qdot, _x.tau, _x.q_out, _x.qd_out, _x.tau_out, _x.temperature, _x.homed, _x.locked,) = _get_struct_9d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_9d = None
def _get_struct_9d():
    global _struct_9d
    if _struct_9d is None:
        _struct_9d = struct.Struct("<9d")
    return _struct_9d
