# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from perception_msgs/WheelchairPose.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class WheelchairPose(genpy.Message):
  _md5sum = "485ac9002407bfc7ddf396d70136f84b"
  _type = "perception_msgs/WheelchairPose"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

geometry_msgs/Pose wheelchair
bool wheelchair_detected

geometry_msgs/Pose wheelchair_handle
bool wheelchair_handle_detected

int32 sequence

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['header','wheelchair','wheelchair_detected','wheelchair_handle','wheelchair_handle_detected','sequence']
  _slot_types = ['std_msgs/Header','geometry_msgs/Pose','bool','geometry_msgs/Pose','bool','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,wheelchair,wheelchair_detected,wheelchair_handle,wheelchair_handle_detected,sequence

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(WheelchairPose, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.wheelchair is None:
        self.wheelchair = geometry_msgs.msg.Pose()
      if self.wheelchair_detected is None:
        self.wheelchair_detected = False
      if self.wheelchair_handle is None:
        self.wheelchair_handle = geometry_msgs.msg.Pose()
      if self.wheelchair_handle_detected is None:
        self.wheelchair_handle_detected = False
      if self.sequence is None:
        self.sequence = 0
    else:
      self.header = std_msgs.msg.Header()
      self.wheelchair = geometry_msgs.msg.Pose()
      self.wheelchair_detected = False
      self.wheelchair_handle = geometry_msgs.msg.Pose()
      self.wheelchair_handle_detected = False
      self.sequence = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7dB7dBi().pack(_x.wheelchair.position.x, _x.wheelchair.position.y, _x.wheelchair.position.z, _x.wheelchair.orientation.x, _x.wheelchair.orientation.y, _x.wheelchair.orientation.z, _x.wheelchair.orientation.w, _x.wheelchair_detected, _x.wheelchair_handle.position.x, _x.wheelchair_handle.position.y, _x.wheelchair_handle.position.z, _x.wheelchair_handle.orientation.x, _x.wheelchair_handle.orientation.y, _x.wheelchair_handle.orientation.z, _x.wheelchair_handle.orientation.w, _x.wheelchair_handle_detected, _x.sequence))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.wheelchair is None:
        self.wheelchair = geometry_msgs.msg.Pose()
      if self.wheelchair_handle is None:
        self.wheelchair_handle = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 118
      (_x.wheelchair.position.x, _x.wheelchair.position.y, _x.wheelchair.position.z, _x.wheelchair.orientation.x, _x.wheelchair.orientation.y, _x.wheelchair.orientation.z, _x.wheelchair.orientation.w, _x.wheelchair_detected, _x.wheelchair_handle.position.x, _x.wheelchair_handle.position.y, _x.wheelchair_handle.position.z, _x.wheelchair_handle.orientation.x, _x.wheelchair_handle.orientation.y, _x.wheelchair_handle.orientation.z, _x.wheelchair_handle.orientation.w, _x.wheelchair_handle_detected, _x.sequence,) = _get_struct_7dB7dBi().unpack(str[start:end])
      self.wheelchair_detected = bool(self.wheelchair_detected)
      self.wheelchair_handle_detected = bool(self.wheelchair_handle_detected)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7dB7dBi().pack(_x.wheelchair.position.x, _x.wheelchair.position.y, _x.wheelchair.position.z, _x.wheelchair.orientation.x, _x.wheelchair.orientation.y, _x.wheelchair.orientation.z, _x.wheelchair.orientation.w, _x.wheelchair_detected, _x.wheelchair_handle.position.x, _x.wheelchair_handle.position.y, _x.wheelchair_handle.position.z, _x.wheelchair_handle.orientation.x, _x.wheelchair_handle.orientation.y, _x.wheelchair_handle.orientation.z, _x.wheelchair_handle.orientation.w, _x.wheelchair_handle_detected, _x.sequence))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.wheelchair is None:
        self.wheelchair = geometry_msgs.msg.Pose()
      if self.wheelchair_handle is None:
        self.wheelchair_handle = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 118
      (_x.wheelchair.position.x, _x.wheelchair.position.y, _x.wheelchair.position.z, _x.wheelchair.orientation.x, _x.wheelchair.orientation.y, _x.wheelchair.orientation.z, _x.wheelchair.orientation.w, _x.wheelchair_detected, _x.wheelchair_handle.position.x, _x.wheelchair_handle.position.y, _x.wheelchair_handle.position.z, _x.wheelchair_handle.orientation.x, _x.wheelchair_handle.orientation.y, _x.wheelchair_handle.orientation.z, _x.wheelchair_handle.orientation.w, _x.wheelchair_handle_detected, _x.sequence,) = _get_struct_7dB7dBi().unpack(str[start:end])
      self.wheelchair_detected = bool(self.wheelchair_detected)
      self.wheelchair_handle_detected = bool(self.wheelchair_handle_detected)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_7dB7dBi = None
def _get_struct_7dB7dBi():
    global _struct_7dB7dBi
    if _struct_7dB7dBi is None:
        _struct_7dB7dBi = struct.Struct("<7dB7dBi")
    return _struct_7dB7dBi
