# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from data_msgs/ComponentObservation.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import multibody_msgs.msg
import std_msgs.msg

class ComponentObservation(genpy.Message):
  _md5sum = "12bd8ea80977c2f8525dc637e3f3ea72"
  _type = "data_msgs/ComponentObservation"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
geometry_msgs/PoseStamped[] track_poses
geometry_msgs/PoseStamped multibody_pose
geometry_msgs/WrenchStamped[] force_torques
multibody_msgs/MultibodyState multibody_state
multibody_msgs/MultibodyCommand multibody_command

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/PoseStamped
# A Pose with reference coordinate frame and timestamp
Header header
Pose pose

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/WrenchStamped
# A wrench with reference coordinate frame and timestamp
Header header
Wrench wrench

================================================================================
MSG: geometry_msgs/Wrench
# This represents force in free space, separated into
# its linear and angular parts.
Vector3  force
Vector3  torque

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: multibody_msgs/MultibodyState
Header header

# This assumes joints are enumerated contiguously from 0, and each joint's name is recorded in corresponding JointConfig.msg.
multibody_msgs/JointState[] states

================================================================================
MSG: multibody_msgs/JointState
float64 q
float64 qdot
float64 tau
float64 q_out
float64 qd_out
float64 tau_out
float64 temperature
# nan: Not available; 0: False; 1: True
float64 homed
float64 locked

================================================================================
MSG: multibody_msgs/MultibodyCommand
Header header

# This assumes joints are enumerated contiguously from 0, and each joint's name is recorded in corresponding JointConfig.msg.
multibody_msgs/JointCommand[] commands

================================================================================
MSG: multibody_msgs/JointCommand
# Refer to `JointOperationMode` in multibody/joint_config.h for detailed definition.
int8 mode
# The length of `values` depends on `mode`.
float64[] values
"""
  __slots__ = ['header','track_poses','multibody_pose','force_torques','multibody_state','multibody_command']
  _slot_types = ['std_msgs/Header','geometry_msgs/PoseStamped[]','geometry_msgs/PoseStamped','geometry_msgs/WrenchStamped[]','multibody_msgs/MultibodyState','multibody_msgs/MultibodyCommand']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,track_poses,multibody_pose,force_torques,multibody_state,multibody_command

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ComponentObservation, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.track_poses is None:
        self.track_poses = []
      if self.multibody_pose is None:
        self.multibody_pose = geometry_msgs.msg.PoseStamped()
      if self.force_torques is None:
        self.force_torques = []
      if self.multibody_state is None:
        self.multibody_state = multibody_msgs.msg.MultibodyState()
      if self.multibody_command is None:
        self.multibody_command = multibody_msgs.msg.MultibodyCommand()
    else:
      self.header = std_msgs.msg.Header()
      self.track_poses = []
      self.multibody_pose = geometry_msgs.msg.PoseStamped()
      self.force_torques = []
      self.multibody_state = multibody_msgs.msg.MultibodyState()
      self.multibody_command = multibody_msgs.msg.MultibodyCommand()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.track_poses)
      buff.write(_struct_I.pack(length))
      for val1 in self.track_poses:
        _v1 = val1.header
        _x = _v1.seq
        buff.write(_get_struct_I().pack(_x))
        _v2 = _v1.stamp
        _x = _v2
        buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
        _x = _v1.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v3 = val1.pose
        _v4 = _v3.position
        _x = _v4
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v5 = _v3.orientation
        _x = _v5
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
      _x = self
      buff.write(_get_struct_3I().pack(_x.multibody_pose.header.seq, _x.multibody_pose.header.stamp.secs, _x.multibody_pose.header.stamp.nsecs))
      _x = self.multibody_pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d().pack(_x.multibody_pose.pose.position.x, _x.multibody_pose.pose.position.y, _x.multibody_pose.pose.position.z, _x.multibody_pose.pose.orientation.x, _x.multibody_pose.pose.orientation.y, _x.multibody_pose.pose.orientation.z, _x.multibody_pose.pose.orientation.w))
      length = len(self.force_torques)
      buff.write(_struct_I.pack(length))
      for val1 in self.force_torques:
        _v6 = val1.header
        _x = _v6.seq
        buff.write(_get_struct_I().pack(_x))
        _v7 = _v6.stamp
        _x = _v7
        buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
        _x = _v6.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v8 = val1.wrench
        _v9 = _v8.force
        _x = _v9
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v10 = _v8.torque
        _x = _v10
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      _x = self
      buff.write(_get_struct_3I().pack(_x.multibody_state.header.seq, _x.multibody_state.header.stamp.secs, _x.multibody_state.header.stamp.nsecs))
      _x = self.multibody_state.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.multibody_state.states)
      buff.write(_struct_I.pack(length))
      for val1 in self.multibody_state.states:
        _x = val1
        buff.write(_get_struct_9d().pack(_x.q, _x.qdot, _x.tau, _x.q_out, _x.qd_out, _x.tau_out, _x.temperature, _x.homed, _x.locked))
      _x = self
      buff.write(_get_struct_3I().pack(_x.multibody_command.header.seq, _x.multibody_command.header.stamp.secs, _x.multibody_command.header.stamp.nsecs))
      _x = self.multibody_command.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.multibody_command.commands)
      buff.write(_struct_I.pack(length))
      for val1 in self.multibody_command.commands:
        _x = val1.mode
        buff.write(_get_struct_b().pack(_x))
        length = len(val1.values)
        buff.write(_struct_I.pack(length))
        pattern = '<%sd'%length
        buff.write(struct.Struct(pattern).pack(*val1.values))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.track_poses is None:
        self.track_poses = None
      if self.multibody_pose is None:
        self.multibody_pose = geometry_msgs.msg.PoseStamped()
      if self.force_torques is None:
        self.force_torques = None
      if self.multibody_state is None:
        self.multibody_state = multibody_msgs.msg.MultibodyState()
      if self.multibody_command is None:
        self.multibody_command = multibody_msgs.msg.MultibodyCommand()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.track_poses = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.PoseStamped()
        _v11 = val1.header
        start = end
        end += 4
        (_v11.seq,) = _get_struct_I().unpack(str[start:end])
        _v12 = _v11.stamp
        _x = _v12
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v11.frame_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v11.frame_id = str[start:end]
        _v13 = val1.pose
        _v14 = _v13.position
        _x = _v14
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v15 = _v13.orientation
        _x = _v15
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        self.track_poses.append(val1)
      _x = self
      start = end
      end += 12
      (_x.multibody_pose.header.seq, _x.multibody_pose.header.stamp.secs, _x.multibody_pose.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.multibody_pose.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.multibody_pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.multibody_pose.pose.position.x, _x.multibody_pose.pose.position.y, _x.multibody_pose.pose.position.z, _x.multibody_pose.pose.orientation.x, _x.multibody_pose.pose.orientation.y, _x.multibody_pose.pose.orientation.z, _x.multibody_pose.pose.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.force_torques = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.WrenchStamped()
        _v16 = val1.header
        start = end
        end += 4
        (_v16.seq,) = _get_struct_I().unpack(str[start:end])
        _v17 = _v16.stamp
        _x = _v17
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v16.frame_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v16.frame_id = str[start:end]
        _v18 = val1.wrench
        _v19 = _v18.force
        _x = _v19
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v20 = _v18.torque
        _x = _v20
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.force_torques.append(val1)
      _x = self
      start = end
      end += 12
      (_x.multibody_state.header.seq, _x.multibody_state.header.stamp.secs, _x.multibody_state.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.multibody_state.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.multibody_state.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.multibody_state.states = []
      for i in range(0, length):
        val1 = multibody_msgs.msg.JointState()
        _x = val1
        start = end
        end += 72
        (_x.q, _x.qdot, _x.tau, _x.q_out, _x.qd_out, _x.tau_out, _x.temperature, _x.homed, _x.locked,) = _get_struct_9d().unpack(str[start:end])
        self.multibody_state.states.append(val1)
      _x = self
      start = end
      end += 12
      (_x.multibody_command.header.seq, _x.multibody_command.header.stamp.secs, _x.multibody_command.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.multibody_command.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.multibody_command.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.multibody_command.commands = []
      for i in range(0, length):
        val1 = multibody_msgs.msg.JointCommand()
        start = end
        end += 1
        (val1.mode,) = _get_struct_b().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sd'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.values = s.unpack(str[start:end])
        self.multibody_command.commands.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.track_poses)
      buff.write(_struct_I.pack(length))
      for val1 in self.track_poses:
        _v21 = val1.header
        _x = _v21.seq
        buff.write(_get_struct_I().pack(_x))
        _v22 = _v21.stamp
        _x = _v22
        buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
        _x = _v21.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v23 = val1.pose
        _v24 = _v23.position
        _x = _v24
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v25 = _v23.orientation
        _x = _v25
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
      _x = self
      buff.write(_get_struct_3I().pack(_x.multibody_pose.header.seq, _x.multibody_pose.header.stamp.secs, _x.multibody_pose.header.stamp.nsecs))
      _x = self.multibody_pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d().pack(_x.multibody_pose.pose.position.x, _x.multibody_pose.pose.position.y, _x.multibody_pose.pose.position.z, _x.multibody_pose.pose.orientation.x, _x.multibody_pose.pose.orientation.y, _x.multibody_pose.pose.orientation.z, _x.multibody_pose.pose.orientation.w))
      length = len(self.force_torques)
      buff.write(_struct_I.pack(length))
      for val1 in self.force_torques:
        _v26 = val1.header
        _x = _v26.seq
        buff.write(_get_struct_I().pack(_x))
        _v27 = _v26.stamp
        _x = _v27
        buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
        _x = _v26.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v28 = val1.wrench
        _v29 = _v28.force
        _x = _v29
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v30 = _v28.torque
        _x = _v30
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      _x = self
      buff.write(_get_struct_3I().pack(_x.multibody_state.header.seq, _x.multibody_state.header.stamp.secs, _x.multibody_state.header.stamp.nsecs))
      _x = self.multibody_state.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.multibody_state.states)
      buff.write(_struct_I.pack(length))
      for val1 in self.multibody_state.states:
        _x = val1
        buff.write(_get_struct_9d().pack(_x.q, _x.qdot, _x.tau, _x.q_out, _x.qd_out, _x.tau_out, _x.temperature, _x.homed, _x.locked))
      _x = self
      buff.write(_get_struct_3I().pack(_x.multibody_command.header.seq, _x.multibody_command.header.stamp.secs, _x.multibody_command.header.stamp.nsecs))
      _x = self.multibody_command.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.multibody_command.commands)
      buff.write(_struct_I.pack(length))
      for val1 in self.multibody_command.commands:
        _x = val1.mode
        buff.write(_get_struct_b().pack(_x))
        length = len(val1.values)
        buff.write(_struct_I.pack(length))
        pattern = '<%sd'%length
        buff.write(val1.values.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.track_poses is None:
        self.track_poses = None
      if self.multibody_pose is None:
        self.multibody_pose = geometry_msgs.msg.PoseStamped()
      if self.force_torques is None:
        self.force_torques = None
      if self.multibody_state is None:
        self.multibody_state = multibody_msgs.msg.MultibodyState()
      if self.multibody_command is None:
        self.multibody_command = multibody_msgs.msg.MultibodyCommand()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.track_poses = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.PoseStamped()
        _v31 = val1.header
        start = end
        end += 4
        (_v31.seq,) = _get_struct_I().unpack(str[start:end])
        _v32 = _v31.stamp
        _x = _v32
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v31.frame_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v31.frame_id = str[start:end]
        _v33 = val1.pose
        _v34 = _v33.position
        _x = _v34
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v35 = _v33.orientation
        _x = _v35
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        self.track_poses.append(val1)
      _x = self
      start = end
      end += 12
      (_x.multibody_pose.header.seq, _x.multibody_pose.header.stamp.secs, _x.multibody_pose.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.multibody_pose.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.multibody_pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.multibody_pose.pose.position.x, _x.multibody_pose.pose.position.y, _x.multibody_pose.pose.position.z, _x.multibody_pose.pose.orientation.x, _x.multibody_pose.pose.orientation.y, _x.multibody_pose.pose.orientation.z, _x.multibody_pose.pose.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.force_torques = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.WrenchStamped()
        _v36 = val1.header
        start = end
        end += 4
        (_v36.seq,) = _get_struct_I().unpack(str[start:end])
        _v37 = _v36.stamp
        _x = _v37
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v36.frame_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v36.frame_id = str[start:end]
        _v38 = val1.wrench
        _v39 = _v38.force
        _x = _v39
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v40 = _v38.torque
        _x = _v40
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.force_torques.append(val1)
      _x = self
      start = end
      end += 12
      (_x.multibody_state.header.seq, _x.multibody_state.header.stamp.secs, _x.multibody_state.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.multibody_state.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.multibody_state.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.multibody_state.states = []
      for i in range(0, length):
        val1 = multibody_msgs.msg.JointState()
        _x = val1
        start = end
        end += 72
        (_x.q, _x.qdot, _x.tau, _x.q_out, _x.qd_out, _x.tau_out, _x.temperature, _x.homed, _x.locked,) = _get_struct_9d().unpack(str[start:end])
        self.multibody_state.states.append(val1)
      _x = self
      start = end
      end += 12
      (_x.multibody_command.header.seq, _x.multibody_command.header.stamp.secs, _x.multibody_command.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.multibody_command.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.multibody_command.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.multibody_command.commands = []
      for i in range(0, length):
        val1 = multibody_msgs.msg.JointCommand()
        start = end
        end += 1
        (val1.mode,) = _get_struct_b().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sd'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.values = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
        self.multibody_command.commands.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
_struct_7d = None
def _get_struct_7d():
    global _struct_7d
    if _struct_7d is None:
        _struct_7d = struct.Struct("<7d")
    return _struct_7d
_struct_9d = None
def _get_struct_9d():
    global _struct_9d
    if _struct_9d is None:
        _struct_9d = struct.Struct("<9d")
    return _struct_9d
_struct_b = None
def _get_struct_b():
    global _struct_b
    if _struct_b is None:
        _struct_b = struct.Struct("<b")
    return _struct_b
