# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from data_msgs/ComponentAction.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class ComponentAction(genpy.Message):
  _md5sum = "7ec0fc5d2871d1b4692f86b639c9c48f"
  _type = "data_msgs/ComponentAction"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
geometry_msgs/PoseStamped pose_command
geometry_msgs/WrenchStamped force_command
float64[] joint_commands
float64 duration

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/PoseStamped
# A Pose with reference coordinate frame and timestamp
Header header
Pose pose

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/WrenchStamped
# A wrench with reference coordinate frame and timestamp
Header header
Wrench wrench

================================================================================
MSG: geometry_msgs/Wrench
# This represents force in free space, separated into
# its linear and angular parts.
Vector3  force
Vector3  torque

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['header','pose_command','force_command','joint_commands','duration']
  _slot_types = ['std_msgs/Header','geometry_msgs/PoseStamped','geometry_msgs/WrenchStamped','float64[]','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,pose_command,force_command,joint_commands,duration

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ComponentAction, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.pose_command is None:
        self.pose_command = geometry_msgs.msg.PoseStamped()
      if self.force_command is None:
        self.force_command = geometry_msgs.msg.WrenchStamped()
      if self.joint_commands is None:
        self.joint_commands = []
      if self.duration is None:
        self.duration = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.pose_command = geometry_msgs.msg.PoseStamped()
      self.force_command = geometry_msgs.msg.WrenchStamped()
      self.joint_commands = []
      self.duration = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.pose_command.header.seq, _x.pose_command.header.stamp.secs, _x.pose_command.header.stamp.nsecs))
      _x = self.pose_command.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d3I().pack(_x.pose_command.pose.position.x, _x.pose_command.pose.position.y, _x.pose_command.pose.position.z, _x.pose_command.pose.orientation.x, _x.pose_command.pose.orientation.y, _x.pose_command.pose.orientation.z, _x.pose_command.pose.orientation.w, _x.force_command.header.seq, _x.force_command.header.stamp.secs, _x.force_command.header.stamp.nsecs))
      _x = self.force_command.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_6d().pack(_x.force_command.wrench.force.x, _x.force_command.wrench.force.y, _x.force_command.wrench.force.z, _x.force_command.wrench.torque.x, _x.force_command.wrench.torque.y, _x.force_command.wrench.torque.z))
      length = len(self.joint_commands)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.joint_commands))
      _x = self.duration
      buff.write(_get_struct_d().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.pose_command is None:
        self.pose_command = geometry_msgs.msg.PoseStamped()
      if self.force_command is None:
        self.force_command = geometry_msgs.msg.WrenchStamped()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.pose_command.header.seq, _x.pose_command.header.stamp.secs, _x.pose_command.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pose_command.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.pose_command.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.pose_command.pose.position.x, _x.pose_command.pose.position.y, _x.pose_command.pose.position.z, _x.pose_command.pose.orientation.x, _x.pose_command.pose.orientation.y, _x.pose_command.pose.orientation.z, _x.pose_command.pose.orientation.w, _x.force_command.header.seq, _x.force_command.header.stamp.secs, _x.force_command.header.stamp.nsecs,) = _get_struct_7d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.force_command.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.force_command.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 48
      (_x.force_command.wrench.force.x, _x.force_command.wrench.force.y, _x.force_command.wrench.force.z, _x.force_command.wrench.torque.x, _x.force_command.wrench.torque.y, _x.force_command.wrench.torque.z,) = _get_struct_6d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.joint_commands = s.unpack(str[start:end])
      start = end
      end += 8
      (self.duration,) = _get_struct_d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.pose_command.header.seq, _x.pose_command.header.stamp.secs, _x.pose_command.header.stamp.nsecs))
      _x = self.pose_command.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d3I().pack(_x.pose_command.pose.position.x, _x.pose_command.pose.position.y, _x.pose_command.pose.position.z, _x.pose_command.pose.orientation.x, _x.pose_command.pose.orientation.y, _x.pose_command.pose.orientation.z, _x.pose_command.pose.orientation.w, _x.force_command.header.seq, _x.force_command.header.stamp.secs, _x.force_command.header.stamp.nsecs))
      _x = self.force_command.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_6d().pack(_x.force_command.wrench.force.x, _x.force_command.wrench.force.y, _x.force_command.wrench.force.z, _x.force_command.wrench.torque.x, _x.force_command.wrench.torque.y, _x.force_command.wrench.torque.z))
      length = len(self.joint_commands)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.joint_commands.tostring())
      _x = self.duration
      buff.write(_get_struct_d().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.pose_command is None:
        self.pose_command = geometry_msgs.msg.PoseStamped()
      if self.force_command is None:
        self.force_command = geometry_msgs.msg.WrenchStamped()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.pose_command.header.seq, _x.pose_command.header.stamp.secs, _x.pose_command.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pose_command.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.pose_command.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.pose_command.pose.position.x, _x.pose_command.pose.position.y, _x.pose_command.pose.position.z, _x.pose_command.pose.orientation.x, _x.pose_command.pose.orientation.y, _x.pose_command.pose.orientation.z, _x.pose_command.pose.orientation.w, _x.force_command.header.seq, _x.force_command.header.stamp.secs, _x.force_command.header.stamp.nsecs,) = _get_struct_7d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.force_command.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.force_command.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 48
      (_x.force_command.wrench.force.x, _x.force_command.wrench.force.y, _x.force_command.wrench.force.z, _x.force_command.wrench.torque.x, _x.force_command.wrench.torque.y, _x.force_command.wrench.torque.z,) = _get_struct_6d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.joint_commands = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 8
      (self.duration,) = _get_struct_d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
_struct_7d3I = None
def _get_struct_7d3I():
    global _struct_7d3I
    if _struct_7d3I is None:
        _struct_7d3I = struct.Struct("<7d3I")
    return _struct_7d3I
_struct_d = None
def _get_struct_d():
    global _struct_d
    if _struct_d is None:
        _struct_d = struct.Struct("<d")
    return _struct_d
