# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from perception_msgs/GetObjectInfoRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GetObjectInfoRequest(genpy.Message):
  _md5sum = "2f12226348d323c2e5b2031b3da53f1b"
  _type = "perception_msgs/GetObjectInfoRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Gets object information with the requested object name.
# and returns true and object infomation if get successfully.
string object_name
"""
  __slots__ = ['object_name']
  _slot_types = ['string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       object_name

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GetObjectInfoRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.object_name is None:
        self.object_name = ''
    else:
      self.object_name = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.object_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.object_name = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.object_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.object_name = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from perception_msgs/GetObjectInfoResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import perception_msgs.msg
import std_msgs.msg

class GetObjectInfoResponse(genpy.Message):
  _md5sum = "a18ba5fc4b0bc747ae31087af09915ec"
  _type = "perception_msgs/GetObjectInfoResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool success
perception_msgs/ObjectInfo object_info


================================================================================
MSG: perception_msgs/ObjectInfo
# Latest update timestamp
Header header
# Value could be {'longneckbottle', 'smallshaker', 'largershake', 'wineglass'}
string name
# Describes the context (In which module/sequence/action, any comments) when the object is update
string description
# Status of whether the object is in-hand. Values could be {'left', 'right', 'none'}
string object_in_hand
# The reference frame is the corresponding end-effector frame (when ObjectInHand is either 'left' or 'right'), 
# or the world/torso frame (when ObjectInHand is 'none')
geometry_msgs/Pose pose
geometry_msgs/Point left_top_point
geometry_msgs/Point right_bottom_point


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['success','object_info']
  _slot_types = ['bool','perception_msgs/ObjectInfo']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       success,object_info

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GetObjectInfoResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.success is None:
        self.success = False
      if self.object_info is None:
        self.object_info = perception_msgs.msg.ObjectInfo()
    else:
      self.success = False
      self.object_info = perception_msgs.msg.ObjectInfo()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B3I().pack(_x.success, _x.object_info.header.seq, _x.object_info.header.stamp.secs, _x.object_info.header.stamp.nsecs))
      _x = self.object_info.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.object_info.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.object_info.description
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.object_info.object_in_hand
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_13d().pack(_x.object_info.pose.position.x, _x.object_info.pose.position.y, _x.object_info.pose.position.z, _x.object_info.pose.orientation.x, _x.object_info.pose.orientation.y, _x.object_info.pose.orientation.z, _x.object_info.pose.orientation.w, _x.object_info.left_top_point.x, _x.object_info.left_top_point.y, _x.object_info.left_top_point.z, _x.object_info.right_bottom_point.x, _x.object_info.right_bottom_point.y, _x.object_info.right_bottom_point.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.object_info is None:
        self.object_info = perception_msgs.msg.ObjectInfo()
      end = 0
      _x = self
      start = end
      end += 13
      (_x.success, _x.object_info.header.seq, _x.object_info.header.stamp.secs, _x.object_info.header.stamp.nsecs,) = _get_struct_B3I().unpack(str[start:end])
      self.success = bool(self.success)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object_info.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.object_info.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object_info.name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.object_info.name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object_info.description = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.object_info.description = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object_info.object_in_hand = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.object_info.object_in_hand = str[start:end]
      _x = self
      start = end
      end += 104
      (_x.object_info.pose.position.x, _x.object_info.pose.position.y, _x.object_info.pose.position.z, _x.object_info.pose.orientation.x, _x.object_info.pose.orientation.y, _x.object_info.pose.orientation.z, _x.object_info.pose.orientation.w, _x.object_info.left_top_point.x, _x.object_info.left_top_point.y, _x.object_info.left_top_point.z, _x.object_info.right_bottom_point.x, _x.object_info.right_bottom_point.y, _x.object_info.right_bottom_point.z,) = _get_struct_13d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B3I().pack(_x.success, _x.object_info.header.seq, _x.object_info.header.stamp.secs, _x.object_info.header.stamp.nsecs))
      _x = self.object_info.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.object_info.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.object_info.description
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.object_info.object_in_hand
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_13d().pack(_x.object_info.pose.position.x, _x.object_info.pose.position.y, _x.object_info.pose.position.z, _x.object_info.pose.orientation.x, _x.object_info.pose.orientation.y, _x.object_info.pose.orientation.z, _x.object_info.pose.orientation.w, _x.object_info.left_top_point.x, _x.object_info.left_top_point.y, _x.object_info.left_top_point.z, _x.object_info.right_bottom_point.x, _x.object_info.right_bottom_point.y, _x.object_info.right_bottom_point.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.object_info is None:
        self.object_info = perception_msgs.msg.ObjectInfo()
      end = 0
      _x = self
      start = end
      end += 13
      (_x.success, _x.object_info.header.seq, _x.object_info.header.stamp.secs, _x.object_info.header.stamp.nsecs,) = _get_struct_B3I().unpack(str[start:end])
      self.success = bool(self.success)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object_info.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.object_info.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object_info.name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.object_info.name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object_info.description = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.object_info.description = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object_info.object_in_hand = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.object_info.object_in_hand = str[start:end]
      _x = self
      start = end
      end += 104
      (_x.object_info.pose.position.x, _x.object_info.pose.position.y, _x.object_info.pose.position.z, _x.object_info.pose.orientation.x, _x.object_info.pose.orientation.y, _x.object_info.pose.orientation.z, _x.object_info.pose.orientation.w, _x.object_info.left_top_point.x, _x.object_info.left_top_point.y, _x.object_info.left_top_point.z, _x.object_info.right_bottom_point.x, _x.object_info.right_bottom_point.y, _x.object_info.right_bottom_point.z,) = _get_struct_13d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_13d = None
def _get_struct_13d():
    global _struct_13d
    if _struct_13d is None:
        _struct_13d = struct.Struct("<13d")
    return _struct_13d
_struct_B3I = None
def _get_struct_B3I():
    global _struct_B3I
    if _struct_B3I is None:
        _struct_B3I = struct.Struct("<B3I")
    return _struct_B3I
class GetObjectInfo(object):
  _type          = 'perception_msgs/GetObjectInfo'
  _md5sum = '1cb07fde458969fcb5843d6b3c3e36a2'
  _request_class  = GetObjectInfoRequest
  _response_class = GetObjectInfoResponse
